spring:
  jackson:
    default-property-inclusion: non_null
  datasource:
    url: jdbc:mysql://garbagedb.c7wwb55uozc5.us-west-2.rds.amazonaws.com:3306/garbage
    username: admin
    password: 542245542
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port : 80

logging:
  level:
    org.springframework.jdbc.core: DEBUG